---
title: "Incubator Final Analysis"
author: "Joe Ballenger"
date: "4/6/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(gt) #grammar for tables
library(Rmisc)
library(drc)
library(emmeans)
library(cowplot)
library(lmerTest)
library(multcomp)
library(multcompView)
library(lme4)
library(ggpubr)
library(tidyverse)

```

```{R}
#This code snippet describes temperature changes of soil surface temperature as the growth chamber door is left open

Cal.dat <- read_excel("GC_Temps_March2023.xlsx", sheet = "Calibration", na="NA") %>%
  mutate(Time = as.numeric(Time),
         Soil =as.factor (Soil),
         Tray = as.factor (Tray),
         Temperature = as.numeric (Temperature))

Calb.mean<-summarySE(Cal.dat,measurevar ="Temperature",
                      groupvars = c("Time"),
                      na.rm = T)

```
```{R}

lm_fit <- lm(Temperature ~ Time, data = Cal.dat)

# Extract coefficients
coefficients <- coef(lm_fit)
intercept <- coefficients[1]
slope <- coefficients[2]

# Calculate R^2
r_squared <- summary(lm_fit)$r.squared

# Create the formula text
formula_text <- paste("y =", round(intercept, 2), "+", round(slope, 2), "x")
r2_text <- paste("R² =", round(r_squared, 3))

# Create the plot
TimePlot2 <- ggplot(data = Cal.dat, aes(x = Time, y = Temperature)) +
  geom_point(size = 4, alpha = 0.5) +
  scale_y_continuous(expand = c(0, 0), limits = c(6, 11))+
  ggtitle("Temperature vs Time Growth Chamber Door is Open") +
  labs(x = "Time (Minutes)", y = "Temperature (C)") +
  theme_bw() +
  geom_smooth(method = "lm", se = FALSE, color = "black") +  # Add the regression line
  annotate("text", x = max(Cal.dat$Time) * 0.8, y = 7, 
           label = formula_text, color = "black", size = 5, hjust = 0) +  # Add the formula
  annotate("text", x = max(Cal.dat$Time) * 0.8, y = 6.5, 
           label = r2_text, color = "black", size = 5, hjust = 0)  # Add R²

print(TimePlot2)

ggsave("GCDoorOpen.pdf", TimePlot2,
       width=12, height=8, units="in", dpi=600)

```
```{r}

chamberrecoverydata<-read.csv("2025-05-door-experiment.csv")
temps.dat<-chamberrecoverydata

temps.dat<-temps.dat%>%
  filter(temperature.probe !="devices")%>%
  filter(temperature.usb !="Error:")%>%
  filter(temperature.probe!="-")%>%
  filter(temperature.usb!="-")%>%
  filter(temperature.probe !="Error:")%>%
  filter(temperature.usb !="devices")

temps.dat.hour<-unlist(lapply(str_split(temps.dat$datetime,"-"), FUN = function(l){return(l[4])}))
temps.dat$lights<-temps.dat.hour

temps.dat$datetime<-as.POSIXct(temps.dat$datetime, format = "%Y-%m-%d-%H-%M")

temps.dat$temperature.probe1<-substr(temps.dat$temperature.probe, 1, nchar(temps.dat$temperature.probe)-1)
temps.dat$temperature.probe1<-as.numeric(temps.dat$temperature.probe1)

colors <- c("157.001.001" = "black", "157.001.002"="yellow","157.001.003"="grey","157.001.004" = "blue",
            "157.002.001" = "orange", "157.002.002" = "green", "157.002.003"="purple", "157.002.004"= "pink",
            "157.003.001" = "red", "157.003.002" = "brown", "157.003.003"="cyan", "157.003.004" = "magenta")


temps.dat$datetime1<-as.POSIXct(temps.dat$datetime, format = "%Y-%m-%d %H:%M:%S")
planting_date <- as.POSIXct("2025-05-21 10:17:00", format="%Y-%m-%d %H:%M:%S")
temps.dat$min_after_start <- as.numeric(difftime(temps.dat$datetime1, planting_date, units = "mins"))

TimePlot2 <- ggplot(data = temps.dat, aes(x = temps.dat$min_after_start, y = temps.dat$temperature.probe1)) +
  geom_point(size = 4, alpha = 0.5, color = temps.dat$color) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 15))+
  ggtitle("Temperature Recovery Time") +
  labs(x = "Time (Minutes)", y = "Temperature (C)") +
  theme_bw() 

plot(TimePlot2)

ggsave("GCDoorOpen-recovery.pdf", TimePlot2,
       width=12, height=8, units="in", dpi=600)

```
